export {default as logo} from "./logo.png"
export {default as profile} from "./profile.png"
export {default as BookingApp} from "./BookingApp.png"
export {default as Pokemon} from "./Pokemon.png"
export {default as CRUD} from "./CRUD.png"
export {default as Rick} from "./RickAndMorty.png"